categories:
  Easyshop:
    label: 'Easyshop'
  Easyshop.brand:
    label: 'Brand'
    parent: Easyshop
  Easyshop.emails:
    label: 'Emails'
    parent: Easyshop
  Easyshop.templates:
    label: 'Templates'
    parent: Easyshop
  Easyshop.pagetypes:
    label: 'Page types'
    parent: Easyshop
  Easyshop.gateways:
    label: 'Payment Gateways'
    parent: Easyshop
  Easyshop.gateways.paypal:
    label: 'PayPal'
    parent: Easyshop.gateways
  Easyshop.pages:
    label: 'Pages'
    parent: Easyshop

settings:
  Easyshop.brand.name:
    label: 'Shop name'
    category: Easyshop.brand
    type: string
    default: 'Easyshop'
  Easyshop.emails.orderContact:
    label: 'Email receiver for contact email of order mails'
    category: Easyshop.emails
    type: string
    default: 'contact@localhost'
  Easyshop.emails.orderConfirmation:
    label: 'Email receiver for order confirmations'
    category: Easyshop.emails
    type: string
    default: 'confirmation@localhost'
  Easyshop.templates.layoutRootPath:
    label: 'Layout root path'
    category: Easyshop.templates
    type: string
    default: ''
  Easyshop.templates.templateRootPath:
    label: 'Template root path'
    category: Easyshop.templates
    type: string
    default: ''
  Easyshop.templates.partialRootPath:
    label: 'Partial root path'
    category: Easyshop.templates
    type: string
    default: ''
  Easyshop.pagetypes.order:
    label: 'Page type for checkout page'
    category: Easyshop.pagetypes
    type: integer
    default: 20240828
  Easyshop.gateways.paypal.mode:
    label: 'PayPal mode'
    category: Easyshop.gateways.paypal
    type: string
    default: 'sandbox'
    enum:
      sandbox: 'Sandbox'
      production: 'Production'
  Easyshop.gateways.paypal.clientid:
    label: 'PayPal Client ID'
    category: Easyshop.gateways.paypal
    type: string
    default: ''
  Easyshop.gateways.paypal.secret:
    label: 'PayPal Secret'
    category: Easyshop.gateways.paypal
    type: string
    default: ''
  Easyshop.pages.checkout:
    label: 'Checkout page'
    category: Easyshop.pages
    type: page
    default: 0
  Easyshop.pages.orderForm:
    label: 'Order form page'
    category: Easyshop.pages
    type: page
    default: 0
